name: derivatives-app
services:
  - name: gateway
    image:
      registry_type: GITHUB
      repository: zubrist/derivatives-gateway
      tag: latest
    http_port: 8000
    instance_size_slug: basic-xs
    instance_count: 1
    envs:
      - key: NSE_SERVICE_URL
        value: ${nse.PRIVATE_URL}
      - key: BREAKEVEN_SERVICE_URL
        value: ${breakeven.PRIVATE_URL}
      - key: TZ
        value: Asia/Kolkata

  - name: nse
    image:
      registry_type: GITHUB
      repository: zubrist/derivatives-nse
      tag: latest
    http_port: 8000
    instance_size_slug: basic-xs
    instance_count: 1
    envs:
      - key: NSE_SERVICE_URL
        value: http://localhost:8000/api/v1_0/fetch_data_from_nse
      - key: TZ
        value: Asia/Kolkata

  - name: breakeven
    image:
      registry_type: GITHUB
      repository: zubrist/derivatives-breakeven
      tag: latest
    http_port: 8000
    instance_size_slug: basic-xs
    instance_count: 1
    envs:
      - key: TZ
        value: Asia/Kolkata

  - name: frontend
    image:
      registry_type: GITHUB
      repository: zubrist/derivatives-frontend
      tag: latest
    http_port: 8501
    instance_size_slug: basic-xs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: BACKEND_URL
        value: ${gateway.PUBLIC_URL}
