name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up BuildKit Docker container builder to improve performance
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Gateway Service
      - name: Build and push gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/derivatives-gateway:latest
            ghcr.io/${{ github.repository_owner }}/derivatives-gateway:${{ github.sha }}

      # NSE Service
      - name: Build and push nse image
        uses: docker/build-push-action@v4
        with:
          context: ./nse
          file: ./nse/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/derivatives-nse:latest
            ghcr.io/${{ github.repository_owner }}/derivatives-nse:${{ github.sha }}

      # Breakeven Service
      - name: Build and push breakeven image
        uses: docker/build-push-action@v4
        with:
          context: ./breakeven
          file: ./breakeven/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/derivatives-breakeven:latest
            ghcr.io/${{ github.repository_owner }}/derivatives-breakeven:${{ github.sha }}

      # Frontend Service
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/derivatives-frontend:latest
            ghcr.io/${{ github.repository_owner }}/derivatives-frontend:${{ github.sha }}
